2024-09-06 08:38:35.7795-ERROR-Xim.AppApi.ActionFilters.ExceptionActionFilter-http://localhost/Menus-Insert:
Invalid column name 'created'.
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'created'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteScalarImplAsync[T](IDbConnection cnn, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 1241
   at Xim.Domain.Mssql.Providers.MssqlProvider.ExecuteScalarTextAsync(IDbConnection cnn, String commandText, Object param) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.Domain.Mssql\Providers\MssqlProvider.cs:line 461
   at Xim.Domain.Mssql.Providers.MssqlProvider.ExecuteScalarTextAsync(String commandText, Object param) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.Domain.Mssql\Providers\MssqlProvider.cs:line 455
   at Xim.Domain.Mssql.Base.MssqlRepo`2.InsertAsync[TData](TData item) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.Domain.Mssql\Base\MssqlRepo.cs:line 123
   at Xim.Application.Services.MenuService.CreateAsync(MenuDtoCreate model) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.Application\Services\MenuService.cs:line 53
   at Xim.AppApi.Controllers.MenuController.InsertAsync(MenuDtoCreate model) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.AppApi\Controllers\MenuController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:015d56b8-8f4b-4c93-a347-17ee42ad2cea
Error Number:207,State:1,Class:16

2024-09-06 14:30:49.1487-ERROR-Xim.AppApi.ActionFilters.ExceptionActionFilter-http://localhost/MenuSubs-Insert:
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xim.Application.Services.MenuSubService.CreateAsync(MenuSubDtoCreate model) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.Application\Services\MenuSubService.cs:line 44
   at Xim.AppApi.Controllers.MenuSubController.InsertAsync(MenuSubDtoCreate model) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.AppApi\Controllers\MenuSubController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2024-09-06 14:31:10.2681-ERROR-Xim.AppApi.ActionFilters.ExceptionActionFilter-http://localhost/MenuSubs-Insert:
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xim.Application.Services.MenuSubService.CreateAsync(MenuSubDtoCreate model) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.Application\Services\MenuSubService.cs:line 44
   at Xim.AppApi.Controllers.MenuSubController.InsertAsync(MenuSubDtoCreate model) in D:\Code\Cong TT\CodeCong_PTN\Api\Xim.AppApi\Controllers\MenuSubController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2024-09-06 14:49:05.5620-ERROR-Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware-http://localhost/MenuSubs/47d3aedf-1758-43c6-92b3-cca178fcaba4-:
An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Xim.AppApi.Controllers.MenuSubController.GetAsync (Xim.AppApi)
Xim.AppApi.Controllers.MenuSubController.GetbyMenuIdAsync (Xim.AppApi)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

2024-09-06 14:49:25.6693-ERROR-Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware-http://localhost/MenuSubs/47d3aedf-1758-43c6-92b3-cca178fcaba4-:
An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Xim.AppApi.Controllers.MenuSubController.GetAsync (Xim.AppApi)
Xim.AppApi.Controllers.MenuSubController.GetbyMenuIdAsync (Xim.AppApi)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

